AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda function which receives a message from an SQS queue, does some data processing and saves the resulting JSON to an S3 bucket.
Resources:
  enrichmovies:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::459727908782:role/enrich_movies_role'
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 1
  FilmQueue:
    Type: 'AWS::SQS::Queue'
    Properties: {}
