AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda function which receives a message from an SQS queue, does some data processing and saves the resulting JSON to an S3 bucket.
Resources:
  enrichmovies:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: enrich_and_store.py.handle_sqs_event
      Runtime: python3.9
      CodeUri: "s3://enrich-code/enrich_movies-87cf199a-7a32-4ad3-af37-1fb702902b1d.zip"
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::459727908782:role/enrich_movies_role'
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - FilmQueue
                - Arn
            BatchSize: 1
  FilmQueue:
    Type: 'AWS::SQS::Queue'
    Properties: {}
