AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda function to pull data from an S3 bucket, filter and queue a message to an SQS queue. 
Resources:
  gettop10movies:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: get_data.py.get_data_and_queue_message
      Runtime: python3.9
      CodeUri: "s3://get-code/get_top10_movies-0a8d769a-7d4a-4982-889e-0bc5436c7988.zip"
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::459727908782:role/get_top10_movies_role'
      Events:
        DailyTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
